stages:
  - run_script

run_script:
  stage: run_script
  script:
    - python3 main.py # Rediriger la sortie vers un fichier

schedule:
  - cron: "0 */6 * * *"  # Planification toutes les 6 heures (vous pouvez ajuster cela selon vos besoins)
