name: Update README all day at 00:00

on:
  push:
  workflow_dispatch:
  schedule:
    # Exécute tous les jours à minuit UTC
    - cron: '0 0 * * *'  

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Run Python script
<<<<<<< HEAD
      run: python /main.py  # Mettez le chemin correct vers votre script Python ici

=======
      run: python ./main.py  # Mettez le chemin correct vers votre script Python ici
>>>>>>> 8d7bba306932ae8432cda4ae957228dcd50f01b6

