name: Update README all day at 00:00

on:
  push:
  workflow_dispatch:
  schedule:
    # Exécute tous les jours à 1h UTC
    - cron: '0 1 * * *'

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Run Python script
      run: python main.py  # Mettez le chemin correct vers votre script Python ici

    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: gibaus
        author_email: gibaus@gmail.com
        force: true
        signoff: false
        message: ':memo: README.md updated by Gibot'
      env:
        # This is necessary in order to push a commit to the repo
        GITHUB_TOKEN: ${{PERSONAL_GITHUB_TOKEN}}
