name: Update README all day at 00:00

on:
  push:
  workflow_dispatch:
  schedule:
    # Exécute tous les jours à minuit UTC
    - cron: '0 0 * * *'

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Run Python script
      run: python main.py  # Mettez le chemin correct vers votre script Python ici
